// Data-shape prop names + suffix patterns consumed by the
// `jsx-no-new-array-as-prop` rule. Extracted from the rule file so
// the analysis stays focused; behaviour-neutral.

// Data-collection-shape prop names that conventionally receive an
// inline array literal: list/table/menu/chart components, command
// palettes, tabs, etc. all take a `data` / `items` / `options` /
// `tabs` / `series` array. Flagging these creates noise on every
// library consumer without surfacing actual perf bugs.
export const DATA_ARRAY_PROP_NAMES: ReadonlySet<string> = new Set([
  // Generic data slots
  "data",
  "items",
  "options",
  "entries",
  "list",
  "dataset",
  "elements",
  "values",
  // Domain-specific collections
  "tabs",
  "columns",
  "rows",
  "pages",
  "categories",
  "tags",
  "keywords",
  "files",
  "blocks",
  "entities",
  "shapes",
  "events",
  "messages",
  "users",
  "series",
  "datasets",
  "children",
  "subRows",
  "nodes",
  "edges",
  // Chart / virtualization specifics
  "size",
  "ticks",
  "yAxis",
  "xAxis",
  // Picker / list / menu / command palette
  "actions",
  "commands",
  "customCommandPaletteItems",
  "renderingShapes",
  "calendarEvents",
  // Chart / visualization series
  "bars",
  "trails",
  "lines",
  "areas",
  "marks",
  "points",
  "labels",
  // Filter / selection collections
  "filters",
  "selectedValues",
  "resources",
  "propertyFilters",
  "dayTimes",
  // UI: nav / menu / shortcut / keybind / hotkey collections
  "links",
  "panels",
  "shortcuts",
  "hotkeys",
  "keybind",
  "keybinds",
  "modifiers",
  // Generic-but-conventional data sources
  "dataSource",
  "suggestions",
  "people",
  "tasks",
  "colors",
  // Domain / taxonomy
  "nouns",
  "verbs",
  "iconButtons",
  // Layout / breadcrumb
  "breadcrumbs",
  "fallbackPlacements",
  // Generic value-as-collection (multi-select, multi-tag controls)
  "value",
  "currentValue",
  // Common domain collections (corpus-derived)
  "listParts",
  "objectNameSingulars",
  "tagsAvailable",
  "properties",
  "middleware",
  "middlewares",
  "variants",
  "surveys",
  "choices",
  "layers",
  "models",
  "roles",
  "metrics",
  "teams",
  "additionalActions",
  "additionalRefs",
  "addonFeatures",
  "operatorAllowlist",
  "goalLines",
  "selectedProperties",
  "panelActions",
  "operandsForFilterType",
  "dataWarehousePopoverFields",
  // Additional common patterns
  "avatars",
  "participants",
  "members",
  "accounts",
  "workspaces",
  "projects",
  "folders",
  "notes",
  "comments",
  "notifications",
  "posts",
  "threads",
  "authors",
  "recipients",
  "subscribers",
  "selections",
  "versions",
  "branches",
  "commits",
  "releases",
  "builds",
  "deployments",
  "jobs",
  "stages",
  "phases",
  "milestones",
  "cards",
  "tiles",
  "slides",
  "routes",
  "permissions",
  "capabilities",
  "settings",
  "attributes",
  "aspects",
  "stats",
  "statistics",
  "insights",
  "findings",
  "issues",
  "tickets",
  "bugs",
  "defects",
  "annotations",
  "markers",
  "pins",
  "stickers",
  "tools",
  "plugins",
  "extensions",
  "modules",
  "services",
  "providers",
  "adapters",
  "helpers",
  "validators",
  "transformers",
  "formatters",
  "serializers",
  "parsers",
  "vehicles",
  "devices",
]);

// Suffix patterns: `*Items`, `*Options`, `*Tabs`, `*Columns`, `*Rows`,
// `*List`, `*Series`, `*Categories`, `*Events`, `*Entries`, `*Elements`,
// `*Shapes`, `*Children`, `*Nodes`, `*Edges`, `*Data`, `*Collection`,
// `*Models`, `*Records`, `*Filters`, `*Values`, `*Times`, `*Resources`.
export const DATA_ARRAY_PROP_SUFFIXES: ReadonlyArray<string> = [
  // `*Props` are pass-through prop bags (Radix / MUI / antd MemoInput
  // watch-lists) whose identity the consumer deliberately handles —
  // mirrors CONFIG_OBJECT_PROP_SUFFIXES in the object-rule tables.
  "Props",
  "Items",
  "Options",
  "Tabs",
  "Columns",
  "Rows",
  "List",
  "Series",
  "Categories",
  "Events",
  "Entries",
  "Elements",
  "Shapes",
  "Children",
  "Nodes",
  "Edges",
  "Data",
  "Collection",
  "Collections",
  "Models",
  "Records",
  "Filters",
  "Values",
  "Times",
  "Resources",
  // More plural collection suffixes
  "Types",
  "Ids",
  "IdArray",
  "IDs",
  "Names",
  "Tags",
  "Keys",
  "Labels",
  "Groups",
  "Buttons",
  "Icons",
  "Links",
  "Steps",
  "Stages",
  "Sources",
  "Targets",
  "Suggestions",
  "Operations",
  "Contexts",
  "Placements",
  "Breadcrumbs",
  "Hotkeys",
  "Shortcuts",
  "Panels",
  "Actions",
  "Activities",
  "Avatars",
  "Participants",
  "Members",
  "Users",
  "Accounts",
  "Workspaces",
  "Projects",
  "Files",
  "Folders",
  "Notes",
  "Comments",
  "Messages",
  "Notifications",
  "Posts",
  "Threads",
  "Authors",
  "Recipients",
  "Subscribers",
  "Choices",
  "Selections",
  "Variants",
  "Versions",
  "Branches",
  "Commits",
  "Releases",
  "Builds",
  "Deployments",
  "Jobs",
  "Tasks",
  "Phases",
  "Milestones",
  "Cards",
  "Tiles",
  "Slides",
  "Pages",
  "Routes",
  "Roles",
  "Permissions",
  "Capabilities",
  "Settings",
  "Properties",
  "Attributes",
  "Aspects",
  "Metrics",
  "Stats",
  "Statistics",
  "Insights",
  "Findings",
  "Issues",
  "Tickets",
  "Bugs",
  "Defects",
  "Annotations",
  "Markers",
  "Pins",
  "Stickers",
  "Tools",
  "Plugins",
  "Extensions",
  "Modules",
  "Services",
  "Providers",
  "Adapters",
  "Helpers",
  "Validators",
  "Transformers",
  "Formatters",
  "Serializers",
  "Parsers",
  "Vehicles",
  "Devices",
];
