import { MIN_OVERPRECISE_SVG_TOKEN_OCCURRENCES } from "../../constants/thresholds.js";
import { defineRule } from "../../utils/define-rule.js";
import { normalizeFilename } from "../../utils/normalize-filename.js";
import type { RuleContext } from "../../utils/rule-context.js";
import { isNodeOfType } from "../../utils/is-node-of-type.js";
import type { EsTreeNodeOfType } from "../../utils/es-tree-node-of-type.js";

const SVG_PATH_HIGH_PRECISION_PATTERN = /\d+\.(\d{4,})/g;

const SVG_PATH_ATTRIBUTES = new Set(["d", "points", "transform"]);

// Rounding to 2 decimals is what the recommendation asks for, so a token is
// only over-precise when a nonzero digit survives past that point. Sketch
// exports pad every transform with zeros (`translate(-495.000000, -71.000000)`)
// — those values are exact integers with no precision to round away.
const VISIBLE_DECIMAL_DIGITS = 2;

const countHighPrecisionTokenOccurrences = (value: string): number => {
  let count = 0;
  for (const match of value.matchAll(SVG_PATH_HIGH_PRECISION_PATTERN)) {
    const decimals = match[1];
    if (decimals === undefined) continue;
    if (/[1-9]/.test(decimals.slice(VISIBLE_DECIMAL_DIGITS))) count += 1;
  }
  return count;
};

// Directory segments that EXPLICITLY signal machine-generated output
// — codegen sinks, design-tool export folders. The high-precision
// paths there come from the exporter, not the engineer; flagging
// them is unactionable noise (re-export reintroduces the precision).
//
// NOTE: deliberately narrow. Earlier broader heuristics (`/icons/`,
// `/icon/`, `/svg/`, `/svgs/`, `/brand/`, `/logo/`, `/logos/`,
// `/flags/`, `/emoji/`, `/emojis/`, `<*Icon>.tsx` basenames) hid
// thousands of real TPs on hand-written, hand-maintained icon
// components (react-grab/icons/*, posthog/icons.tsx, plane/empty-state/
// assets/*). Those are bytes the dev OWNS and CAN optimise — keep
// flagging them.
const AUTO_GENERATED_PATH_SEGMENTS: ReadonlyArray<string> = [
  "/__generated__/",
  "/generated/",
  "/codegen/",
  "/figma-export/",
  "/sketch-export/",
];

const isAutoGeneratedSvgFile = (filename: string | undefined): boolean => {
  if (!filename) return false;
  for (const segment of AUTO_GENERATED_PATH_SEGMENTS) {
    if (filename.includes(segment)) return true;
  }
  return false;
};

// HACK: SVG path strings with 4+ decimals (e.g. `M 10.293847 20.847362`)
// add bytes for sub-pixel precision the user can't see. Most editors
// emit these by default; truncating to 1–2 decimals trims 30–50% off
// markup with no visible difference.
export const renderingSvgPrecision = defineRule({
  id: "rendering-svg-precision",
  title: "Overly precise SVG path values",
  severity: "warn",
  category: "Performance",
  tags: ["test-noise"],
  recommendation:
    "Round path, points, and transform decimals to 1 or 2 digits. The extra precision adds bytes with no visible difference.",
  create: (context: RuleContext) => {
    const filename = context.filename;
    const isAutoGenerated = isAutoGeneratedSvgFile(
      filename ? normalizeFilename(filename) : undefined,
    );
    // The root cause is one exported asset per file: a pasted icon fires on
    // every d/points/transform inside it, and the fix (round the decimals /
    // run SVGO) is applied file-wide. One report per file is enough.
    let didReportFile = false;
    return {
      JSXAttribute(node: EsTreeNodeOfType<"JSXAttribute">) {
        if (isAutoGenerated) return;
        if (didReportFile) return;
        if (!isNodeOfType(node.name, "JSXIdentifier")) return;
        if (!SVG_PATH_ATTRIBUTES.has(node.name.name)) return;
        if (!isNodeOfType(node.value, "Literal")) return;
        const value = node.value.value;
        if (typeof value !== "string") return;
        if (countHighPrecisionTokenOccurrences(value) < MIN_OVERPRECISE_SVG_TOKEN_OCCURRENCES)
          return;

        didReportFile = true;
        context.report({
          node,
          message: `Your users download extra bytes for SVG ${node.name.name} precision they can't see, so round it to 1 or 2 decimals.`,
        });
      },
    };
  },
});
